USE p5g8
GO

CREATE TABLE WineDB.Pessoa (
	Nome		VARCHAR(256)	NOT NULL,
	Morada		VARCHAR(256)	NOT NULL,
	NIF			INT				NOT NULL,
	Data_Nasc	VARCHAR(10)		NOT NULL,
	Genero		VARCHAR(1),
	Telemovel	VARCHAR(9),

	PRIMARY KEY (NIF)
);
GO
DROP TABLE WineDB.Pessoa

CREATE TABLE WineDB.Cliente (
	NIF			INT		NOT NULL,

	PRIMARY KEY (NIF),
	FOREIGN KEY (NIF) REFERENCES WineDB.Pessoa(NIF) ON UPDATE CASCADE ON DELETE CASCADE
);
GO
DROP TABLE WineDB.Cliente

CREATE TABLE WineDB.Funcionario(
	NIF						INT				NOT NULL,
	IBAN					VARCHAR(25)		NOT NULL,
	Num_SS					INT				NOT NULL,
	Data_Inicio_Atividade	VARCHAR(10)		NOT NULL,

	PRIMARY KEY (NIF),
	FOREIGN KEY (NIF) REFERENCES WineDB.Pessoa(NIF) ON UPDATE CASCADE ON DELETE CASCADE
);
GO
DROP TABLE WineDB.Funcionario

CREATE TABLE WineDB.Gerente(
	NIF			INT				NOT NULL,
	Num_Func	INT				NOT NULL,

	PRIMARY KEY (NIF),
	FOREIGN KEY (NIF) REFERENCES WineDB.Funcionario(NIF) ON UPDATE CASCADE,
);
GO
DROP TABLE WineDB.Gerente

CREATE TABLE WineDB.Adega (
	ID				VARCHAR(5)		NOT NULL,
	Nome			VARCHAR(256)	NOT NULL,
	Endereco		VARCHAR(256)	NOT NULL,
	Cap_Max			FLOAT			DEFAULT 0,
	Num_Cubas		INT				DEFAULT 0,
	NIF_Gerente		INT				NOT NULL,		

	PRIMARY KEY (ID),
	FOREIGN KEY (NIF_Gerente) REFERENCES WineDB.Gerente(NIF) ON UPDATE CASCADE
);
GO
DROP TABLE WineDB.Adega

CREATE TABLE WineDB.OperadorAdega (
	NIF			INT				NOT NULL,
	Num_Func	INT				NOT NULL,
	ID_Adega	VARCHAR(5)		,

	PRIMARY KEY (NIF),
	FOREIGN KEY (NIF) REFERENCES WineDB.Funcionario(NIF) ON DELETE CASCADE,
	FOREIGN KEY (ID_Adega) REFERENCES WineDB.Adega(ID) ON DELETE SET NULL,
);
GO
DROP TABLE WineDB.OperadorAdega

CREATE TABLE WineDB.Cuba (
	ID			INT				NOT NULL,
	ID_Adega	VARCHAR(5)		NOT NULL,
	Cap_Max		FLOAT			NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY(ID_Adega) REFERENCES WineDB.Adega(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
GO
DROP TABLE WineDB.Cuba

CREATE TABLE WineDB.TipoCuba (
	ID			INT				NOT NULL,
	TipoCuba	VARCHAR(64)		NOT NULL,

	PRIMARY KEY (ID, TipoCuba),
	FOREIGN KEY (ID) REFERENCES WineDB.Cuba(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
GO
DROP TABLE WineDB.TipoCuba

CREATE TABLE WineDB.Casta (
	ID				INT				NOT NULL,
	Nome			VARCHAR(128)	NOT NULL,
	Percentagem		FLOAT			NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (ID) REFERENCES WineDB.Cuba(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
GO
DROP TABLE WineDB.Casta

CREATE TABLE WineDB.Terreno (
	ID				VARCHAR(5)		NOT NULL,
	Nome			VARCHAR(256)	NOT NULL,
	Localizacao		VARCHAR(256)	NOT NULL,
	Ano_plantacao	VARCHAR(4), 
	ID_Casta		INT,
	Hectares		FLOAT			NOT NULL,
	ID_Adega		VARCHAR(5)		NOT NULL,
	
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_Adega) REFERENCES WineDB.Adega(ID),
	FOREIGN KEY (ID_Casta) REFERENCES WineDB.Casta(ID),
);
GO
DROP TABLE WineDB.Terreno

CREATE TABLE WineDB.OperadorAgricola(
	NIF				INT				NOT NULL,
	Num_Func		INT				NOT NULL,
	ID_Terreno		VARCHAR(5)		, 

	PRIMARY KEY (NIF),
	FOREIGN KEY (NIF) REFERENCES WineDB.Funcionario(NIF) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (ID_Terreno) REFERENCES WineDB.Terreno(ID) ON UPDATE CASCADE ON DELETE SET NULL,
);
GO
DROP TABLE WineDB.OperadorAgricola

CREATE TABLE WineDB.Vinho (
	ID			VARCHAR(5)		NOT NULL,
	ID_Cuba		INT				NOT NULL,
	Nome		VARCHAR(256)	NOT NULL,
	DOC			VARCHAR(32),
	ID_Casta	INT				NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (ID_Cuba) REFERENCES WineDB.Cuba(ID) ,
	FOREIGN KEY (ID_Casta) REFERENCES WineDB.Casta(ID),
);
GO
DROP TABLE WineDB.Vinho

CREATE TABLE WineDB.Armazem (
	ID					VARCHAR(5)		NOT NULL,
	Localizacao			VARCHAR(256)	NOT NULL,
	Nome				VARCHAR(256)	NOT NULL,
	ID_Adega			VARCHAR(5)		NOT NULL,

	PRIMARY KEY (ID),
	FOREIGN KEY (ID_Adega) REFERENCES WineDB.Adega(ID) ON UPDATE CASCADE,
);
GO
DROP TABLE WineDB.Armazem


CREATE TABLE WineDB.Venda (
	ID_Venda		INT				NOT NULL	IDENTITY,
	ID_Produto		VARCHAR(5)		NOT NULL,
	Preco			FLOAT			NOT NULL,
	IVA				INT				DEFAULT 23,
	Quantidade		INT,
	NIF_Cliente		INT				NOT NULL,

	PRIMARY KEY(ID_Venda),
	FOREIGN KEY (ID_Produto) REFERENCES WineDB.Vinho(ID),
	FOREIGN KEY (NIF_Cliente) REFERENCES WineDB.Cliente(NIF) ON DELETE CASCADE,
);
GO
DROP TABLE WineDB.Venda

Create TABLE WineDB.TipoTrabalho(
	NIF				INT				NOT NULL,
	Tipo_Trabalho	VARCHAR(64),

	PRIMARY KEY (NIF),
	FOREIGN KEY (NIF) REFERENCES WineDB.OperadorAgricola(NIF) ON UPDATE CASCADE,
);
GO
DROP TABLE WineDB.TipoTrabalho

CREATE TABLE WineDB.Armazenado(
	ID_Vinho				VARCHAR(5)		NOT NULL,
	ID_Armazem				VARCHAR(5)		NOT NULL,

	PRIMARY KEY (ID_Vinho, ID_Armazem),
	FOREIGN KEY (ID_Vinho) REFERENCES WineDB.Vinho(ID),
	FOREIGN KEY (ID_Armazem) REFERENCES WineDB.Armazem(ID),
);
GO
DROP TABLE WineDB.Armazenado