USE p5g8
GO

CREATE FUNCTION WineDB.checkIfNIFExists (@NIF INT) RETURNS INT
AS
	BEGIN
		DECLARE @counter INT
		SELECT @counter=COUNT(1) FROM WineDB.Pessoa WHERE NIF=@NIF
		RETURN @counter
	END
GO

CREATE FUNCTION WineDB.checkIfNum_FuncExists (@Num_Func INT) RETURNS INT
AS
	BEGIN
		DECLARE @counter INT
		SELECT @counter=COUNT(1) FROM WineDB.Pessoa WHERE NIF=@NIF
		--VER ISTO PARA VERIICAR NOS 3 TIPOS DE FUNCIONARIO
		RETURN @counter
	END
GO